### ISSUE TITLE
Absolute paths for mods

### ISSUE THREAD

**Issue by igorkis-scrts** [igorkis-scrts/Serverify-A3#6]
**Is your feature request related to a problem? Please describe.**
Users asks for ability to reference mods directly by their file path.

**Describe the solution you'd like**
Add button on the Modifications tab that calls OpenFileDialog that allows user to add mods that are not stored in the main Arma 3 folder.

**Comment by EpsilonCommunity** [comment]
Please add. I've had to move all files from !workshop to root. This was 80GB of mods.
