### ISSUE TITLE
Language XAML for German

### ISSUE THREAD

**Issue by Fallingstorm** [igorkis-scrts/Serverify-A3#7]
Hello, could you integrate the Language XAML for German?
I change the Datafile to TXT.
[Lang.ge-GE.txt](https://github.com/igorkiss/Serverify-A3/files/3489922/Lang.ge-GE.txt)

Is your Original from english changed to German. 
On the File you must only change the txt to xaml.

It would be nice if you can insert it to your Serverify-A3. 

Thank you.

**Comment by igorkiss** [comment]
Hi!
Foremost, thank you for your effort to localize ServerifyA3 into German language!
On topic - yeah, i will add this .xaml file in the app (with your credits, of course). I will schedule german localization (with your credits, of course) into the next update, which will happen in one or two weeks.

Установить Outlook для iOS<https://aka.ms/o0ukef>
________________________________
От: Fallingstorm <notifications@github.com>
Отправлено: Sunday, August 11, 2019 4:56:49 PM
Кому: igorkiss/Serverify-A3 <Serverify-A3@noreply.github.com>
Копия: Subscribed <subscribed@noreply.github.com>
Тема: [igorkiss/Serverify-A3] Language XAML for German (#7)


Hello, could you integrate the Language XAML for German?
I change the Datafile to TXT.
Lang.ge-GE.txt<https://github.com/igorkiss/Serverify-A3/files/3489922/Lang.ge-GE.txt>

Is your Original from english changed to German.
On the File you must only change the txt to xaml.

It would be nice if you can insert it to your Serverify-A3.

Thank you.

**Comment by Fallingstorm** [comment]
Wow thats fine, Thank you.

**Comment by Fallingstorm** [comment]
For the Credits:
i am from the 8th SFG Titan Platoon, titan-platoon.
best regards.

**Comment by igorkis-scrts** [comment]
Resolved.
